use_frameworks!

platform :ios, '8.0'

target 'KLSLibKit_Example' do
  pod 'KLSLibKit', :path => '../'

  target 'KLSLibKit_Tests' do
    inherit! :search_paths

  #  pod 'FBSnapshotTestCase'
  end
end
